version: '3.8'

services:
  web:
    build: './web'
    volumes:
      - ./web/usr/src/app:rw
    ports:
      - 80:80
  
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - datavolume:/data/db
    expose:
      - 27017
    restart: unless-stopped

  volumes:
  datavolume: